[General]
__userfile__=true
lock_command=xsecurelock
lock_screen_before_power_actions=true
power_actions_after_lock_delay=250
window_manager=openbox

[Environment]
XSECURELOCK_AUTH_TIMEOUT=30
XSECURELOCK_BACKGROUND_COLOR=#000000
XSECURELOCK_PASSWORD_PROMPT=asterisks
XSECURELOCK_SAVER=saver_blank
XSECURELOCK_SINGLE_AUTH_WINDOW=1
